[package]
name = "aspartial"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
serde = ["dep:serde"]
serde_json = ["dep:serde_json"]

[dependencies]
aspartial_derive = { path = "../aspartial_derive" }
serde = { workspace = true, optional=true }
serde_json = { workspace = true, optional=true }

